language: java

before_install:
  - sudo add-apt-repository -y ppa:mfikes/planck
  - sudo apt-get -qq update
  - sudo apt-get install -y leiningen planck npm nodejs-legacy
  - sudo npm install -g lumo-cljs

install:
  - jdk_switcher use openjdk8

dist: trusty

script: lein test && lein tach lumo
