os:
  - linux

language: java

before_install:
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.315.sh
  - chmod +x linux-install-1.9.0.315.sh
  - sudo ./linux-install-1.9.0.315.sh

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y javascriptcoregtk-3.0 libglib2.0-dev libzip-dev libcurl4-gnutls-dev
  - git clone https://github.com/mfikes/planck
  - cd planck; script/build; cd ..
  - export PATH=$PATH:planck/planck-c/build

script: 
  - lein test
  - lein tach planck
